HOST: http://nas.hostgator.com/


--- NAS Monitor API v1 ---
---
A RESTful API to be used with the NAS monitor and other scripts related to the NAS backup service.
---

-- Server Resources --


List all servers
GET /servers
> Accept: application/json
< 200
< Content-Type: application/json
{ "servers":[
  { "url": "/servers/samco", "hostname": "samco.websitewelcome.com", "nasAssignment": "nas715.hostgator.com", "lastBackup": "7/29/13 14:00:02", "backupStatus": "Completed", "pctComplete": 100 },
  { "url": "/servers/gator3000", "hostname": "gator3000.hostgator.com", "nasAssignment": "nas905.hostgator.com", "lastBackup": "7/30/13 1:03:47", "backupStatus": "In Progress", "pctComplete": 65 }
]  }

Add a new server to the list.
POST /servers
> Accept: aplication/json
< 201
< Content-Type: application/json
{ "hostname": "gator3010.hostgator.com", "nasAssignment": "nas900.hostgator.com" }

Display a specific server
GET /servers/{hostname}
> Accept: application/json
< 200
< Content-Type: application/json
{ "hostname": "samco.websitewelcome.com", "nasAssignment": "nas715.hostgator.com", "lastBackup": "7/29/13 14:00:02", "backupStatus": "Completed", "pctComplete": 100 }